name: cave-a-vin
services:
  cave-a-vin:
    cpu_shares: 90
    command: []
    container_name: cave-a-vin
    deploy:
      resources:
        limits:
          memory: 1816M
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NITRO_API_TOKEN=${NITRO_API_TOKEN}
      - NITRO_ANTHROPIC_API_KEY=${NITRO_ANTHROPIC_API_KEY}
      - NITRO_GOOGLE_API_KEY=${NITRO_GOOGLE_API_KEY}
      - NITRO_SENTRY_DSN=${NITRO_SENTRY_DSN}
    hostname: cave-a-vin
    image: moifort/cave-a-vin:latest
    labels:
      icon: https://cdn-icons-png.flaticon.com/512/763/763048.png
    ports:
      - target: 3000
        published: "3001"
        protocol: tcp
    pull_policy: always
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/cave-a-vin
        target: /app/.data
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://cdn-icons-png.flaticon.com/512/763/763048.png
  index: /
  is_uncontrolled: false
  port_map: "3001"
  scheme: http
  store_app_id: breathtaking_derek
  title:
    custom: ""
    en_us: cave-a-vin