services:
  canvas-server:
    image: moifort/cave-a-vin:latest
    container_name: canvas-server
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: "3000"
      NITRO_API_TOKEN: ${NITRO_API_TOKEN}
      NITRO_SERVER_URL: http://192.168.0.165:3000
      NITRO_ANTHROPIC_API_KEY: ${NITRO_ANTHROPIC_API_KEY}
      NITRO_GOOGLE_API_KEY: ${NITRO_GOOGLE_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
