mutation AddWine($input: AddBeverageInput!) {
  addBeverage(input: $input) {
    id
    name
    beverageType
    subtype
    details {
      ... on WineDetails {
        color
        vintage
      }
    }
    createdAt
    updatedAt
  }
}

mutation DeleteWine($id: BeverageId!) {
  deleteBeverage(id: $id)
}

mutation MarkFavorite($beverageId: BeverageId!, $favorite: Boolean!) {
  markFavorite(beverageId: $beverageId, favorite: $favorite)
}

mutation SaveWineSheet($id: BeverageId!, $input: BeverageSheetInput!) {
  saveBeverageSheet(id: $id, input: $input) {
    ...WineDetailFields
  }
}
