query Dashboard {
  cellars {
    id
    name
  }
  dashboard {
    bottleCount
    capacity
    totalValue
    readyToDrink {
      id
      name
      beverageType
      color
      cellarId
      position
      urgent
      drinkUntil
    }
    favorites {
      id
      name
      beverageType
      color
      vintage
      estimatedPrice
      tastingDate
      rating
    }
    lastBottle {
      wine {
        id
        name
        beverageType
        color
        vintage
      }
      cellarId
      position
      date
    }
    lastExit {
      type
      date
      beverageId
      beverageName
      beverageProducer
      wineBeverageType
      wineColor
      position
      actor {
        displayName
        isMine
      }
    }
    history {
      type
      date
      beverageId
      beverageName
      beverageProducer
      wineBeverageType
      wineColor
      position
      actor {
        displayName
        isMine
      }
    }
  }
}
