name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *' # 22h CET / 21h UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: renovatebot/github-action@v46.1.6
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
